name: cesm
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  # core scipy packages
  - numpy
  - matplotlib
  - xarray
   # geospatial
  - cartopy
  - basemap
  - basemap-data-hires
  - netcdf4
  - h5py
  - h5netcdf
  # misc
  - python-wget
  - wget
  - pip
  - nc-time-axis
  - cfgrib
  - cesm
  - lftp
  - pip:
      - bioblend 
      - galaxy-ie-helpers
