name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  - sparse
  - sympy
  - pip
  - pip:
      - bioblend 
      - galaxy-ie-helpers
