name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  - sparse
  - sympy
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  - tensorflow
  - keras
  - pytorch-cpu
  - pip
  - pip:
      - bioblend 
      - galaxy-ie-helpers
